package Tablas;
// Generated 12-ene-2021 15:16:35 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * DatosCalidad generated by hbm2java
 */
public class DatosCalidad implements java.io.Serializable {

	private int codDatos;
	private Estaciones estaciones;
	private Date fecha;
	private Date hora;
	private Float comgM3;
	private Float co8hmgM3;
	private Integer nogm3;
	private Integer no2;
	private String no2ica;
	private Integer noxgm3;
	private Float pm10;
	private String pm10ica;
	private Float pm25;
	private String pm25ica;
	private Float so2;
	private String so2ica;
	private String icastation;

	public DatosCalidad() {
	}

	public DatosCalidad(int codDatos, Estaciones estaciones, Date fecha, Date hora) {
		this.codDatos = codDatos;
		this.estaciones = estaciones;
		this.fecha = fecha;
		this.hora = hora;
	}

	public DatosCalidad(int codDatos, Estaciones estaciones, Date fecha, Date hora, Float comgM3, Float co8hmgM3,
			Integer nogm3, Integer no2, String no2ica, Integer noxgm3, Float pm10, String pm10ica, Float pm25,
			String pm25ica, Float so2, String so2ica, String icastation) {
		this.codDatos = codDatos;
		this.estaciones = estaciones;
		this.fecha = fecha;
		this.hora = hora;
		this.comgM3 = comgM3;
		this.co8hmgM3 = co8hmgM3;
		this.nogm3 = nogm3;
		this.no2 = no2;
		this.no2ica = no2ica;
		this.noxgm3 = noxgm3;
		this.pm10 = pm10;
		this.pm10ica = pm10ica;
		this.pm25 = pm25;
		this.pm25ica = pm25ica;
		this.so2 = so2;
		this.so2ica = so2ica;
		this.icastation = icastation;
	}

	public int getCodDatos() {
		return this.codDatos;
	}

	public void setCodDatos(int codDatos) {
		this.codDatos = codDatos;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public Float getComgM3() {
		return this.comgM3;
	}

	public void setComgM3(Float comgM3) {
		this.comgM3 = comgM3;
	}

	public Float getCo8hmgM3() {
		return this.co8hmgM3;
	}

	public void setCo8hmgM3(Float co8hmgM3) {
		this.co8hmgM3 = co8hmgM3;
	}

	public Integer getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(Integer nogm3) {
		this.nogm3 = nogm3;
	}

	public Integer getNo2() {
		return this.no2;
	}

	public void setNo2(Integer no2) {
		this.no2 = no2;
	}

	public String getNo2ica() {
		return this.no2ica;
	}

	public void setNo2ica(String no2ica) {
		this.no2ica = no2ica;
	}

	public Integer getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(Integer noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public Float getPm10() {
		return this.pm10;
	}

	public void setPm10(Float pm10) {
		this.pm10 = pm10;
	}

	public String getPm10ica() {
		return this.pm10ica;
	}

	public void setPm10ica(String pm10ica) {
		this.pm10ica = pm10ica;
	}

	public Float getPm25() {
		return this.pm25;
	}

	public void setPm25(Float pm25) {
		this.pm25 = pm25;
	}

	public String getPm25ica() {
		return this.pm25ica;
	}

	public void setPm25ica(String pm25ica) {
		this.pm25ica = pm25ica;
	}

	public Float getSo2() {
		return this.so2;
	}

	public void setSo2(Float so2) {
		this.so2 = so2;
	}

	public String getSo2ica() {
		return this.so2ica;
	}

	public void setSo2ica(String so2ica) {
		this.so2ica = so2ica;
	}

	public String getIcastation() {
		return this.icastation;
	}

	public void setIcastation(String icastation) {
		this.icastation = icastation;
	}

}
