package Tablas;
// Generated 21-dic-2020 15:41:45 by Hibernate Tools 5.4.18.Final

/**
 * EstaEn generated by hbm2java
 */
public class EstaEn implements java.io.Serializable {

	private EstaEnId id;
	private EspaciosNaturales espaciosNaturales;
	private Municipios municipios;

	public EstaEn() {
	}

	public EstaEn(EstaEnId id, EspaciosNaturales espaciosNaturales, Municipios municipios) {
		this.id = id;
		this.espaciosNaturales = espaciosNaturales;
		this.municipios = municipios;
	}

	public EstaEnId getId() {
		return this.id;
	}

	public void setId(EstaEnId id) {
		this.id = id;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

}
