package Tablas;
// Generated 11-ene-2021 15:35:54 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private int codUsuario;
	private String nombre;
	private String pass;
	private Set favoritoses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int codUsuario, String nombre, String pass) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.pass = pass;
	}

	public Usuarios(int codUsuario, String nombre, String pass, Set favoritoses) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.pass = pass;
		this.favoritoses = favoritoses;
	}

	public int getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Set getFavoritoses() {
		return this.favoritoses;
	}

	public void setFavoritoses(Set favoritoses) {
		this.favoritoses = favoritoses;
	}

}
